### ISSUE TITLE
Changing variable name for shape and its effects on downstream commands involving attributes

### ISSUE THREAD

**Issue by hgclose** [txst-per-group/Glowscript-Blocks#33] opened 2017-05-30 18:16 UTC
- Set a new variable (Var_1) equal to a box
- Construct a vector addition statement involving the position (e.g.) of the box
- Go back to original declaration of variable name and "Rename variable..." to a new name (e.g., Var_2)
- Box's position block is ejected from the addition block. Type of block appears to change from vector to shape.

**Comment by dube1503** [comment] 2017-06-06 18:16
@hgclose Following these recreation steps I'm not so sure this is a bug? Are you saying that the expected behavior of the block should be that renaming the original declaration of the variable should not reset the other forms of the variable? I think having the user required to go through and examine the effect of renaming a variable might not be a negative result

**Comment by hgclose** [comment] 2017-06-06 19:29
I don't know what you are seeing, but yes, I think of it as a bug. If you name just a vector and perform a bunch of operations on it, and then rename the vector at the top, the downstream instances of the vector change their name and their operations don't disintegrate - the blocks don't come apart. I don't have to reassemble all of the statements. However, if the vector is an attribute of a shape, the block is ejected and then I have to put the blocks back together, if I can remember where it went. Sometimes it is hard to see where it popped out from, and even if it did, I don't think I should have to put the statements back together just because the variable has a new name.

**Comment by eah13** [comment] 2017-06-12 18:26
I'd second @hgclose on this. 

Renaming a variable in a definition block in a blocks-based language seems to indicate that the user is changing the variable name globally.  So renaming within a `set` block is equivalent to find/replace all.  In this case, replacing all `item_1`s with the new name, mutator blocks and arguments intact, is the most graceful way to handle what the user means. Otherwise, you could get into a situation where a very developed program falls apart just because a student is going in to title their variables in a more readable way.

All that said, I'm unable to reproduce.  Perhaps this has been fixed via another pull request? Seems like type switching would be the cause and I believe a recent PR affected either the type that was returned or the allowable inputs to the addition or subtraction operators.

**Comment by dube1503** [comment] 2017-06-13 18:26
Yes, i can confirm that a previous commit fixed this issue and i believe @eah13 is correct that it was @codestar12 PR about type switching. It seems this issue was just aside effect caused from turning off the variable type and onchange functionality temporarily before fixing.

**Closed** 2017-06-14 11:21 UTC
Labels: bug
