### ISSUE TITLE
vel, acc, etc. included in "get" blocks for shapes but not in "initialize" blocks

### ISSUE THREAD

**Issue by hgclose** [txst-per-group/Glowscript-Blocks#37] opened 2017-05-30 21:24 UTC
![image](https://cloud.githubusercontent.com/assets/28712067/26605569/3463f0fe-4554-11e7-8485-5d562f62ee35.png)

![image](https://cloud.githubusercontent.com/assets/28712067/26605595/453a905e-4554-11e7-90dd-c6697e820e5b.png)

**Comment by codestar12** [comment] 2017-06-05 16:45
closing this issue as it is a duplicate of issue #24

**Closed by codestar12** 2017-06-05 16:45 UTC
Labels: duplicate
